service: schedule
frameworkVersion: '>=2.0.0'
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  role: ${cf:meeting-insights-resources-${opt:stage}.LambdaExecutionRole}
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - ${self:service}-${opt:stage}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${opt:stage}

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${cf:acloudguru-api-gateway-${opt:stage}.InternalDomainName}
    stage: ${opt:stage}
    basePath: schedule
    certificateName: '*.acloud.guru'
    createRoute53Record: false
    endpointType: 'regional'

package:
  exclude:
    - configure/**
    - coverage/**
    - src/**/*.test.js
    - .node-version
    - '*.sh'
    - package.json
    - yarn.lock
    - README.md

functions:
  macroWebhook:
    handler: src/handlers/macro.handler
    events:
      - http:
          path: graphql
          method: post
    tags:
      FunctionType: stream_handler
